version: '2'
services:
  opendfl:
    restart: always
    image: opendfl-console
    ports:
      - 8080:8080
    # 设置容器 hosts
    extra_hosts:
      - "dockerhost:10.0.8.3"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 200m