# /info端点信息配置
info:
  app:
    name: OpenDFL test demo dev
    version: 0.1

spring:
  redis:
    host: 192.168.0.40
    #password: 'testjd2019'
    port: 6379
    database: 1
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000ms
  etcd:
    endpoints: http://192.168.0.40:2379,http://192.168.0.40:2380,http://192.168.0.40:2381
  zookeeper:
    baseSleepTimeMs: 1000
    #重试次数
    maxRetries: 3
    #zookeeper服务连接id与端口
    address: 192.168.0.40:2181
    #会话超时时间，单位毫秒
    sessionTimeoutMs: 5000
    #连接创建超时时间，单位毫秒
    connection-timeout-ms: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.40:3306/opendfl_dev?allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: opendfl_dev
    password: jh@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    initial-size: 3
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 'x'
    max-wait: 6000
    pool-prepared-statements: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 60000
    web-stat-filter:
      enabled: true
      url-pattern: "/*"


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.ccs.opendfl.mysql
  mapper-locations: classpath:mappers/*/*.xml

# TkMapper
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: true
  enum-as-simple-type: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    org:
      ccs:
        opendfl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
