# /info端点信息配置
info:
  app:
    name: OpenDFL console
    version: 1.1
  redis: ${spring.redis.host}

starter:
  #支持关闭这个服务的Redis配置，由外其他类提供
  redisCacheEnable: 1

spring:
  profiles:
    include:
      - opendfl
      - frequency
      - requestlock
      - console
  redis:
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000ms
  etcd:
    endpoints:
  zookeeper:
    baseSleepTimeMs: 1000
    #重试次数
    maxRetries: 3
    #zookeeper服务连接id与端口
    address:
    #会话超时时间，单位毫秒
    sessionTimeoutMs: 5000
    #连接创建超时时间，单位毫秒
    connection-timeout-ms: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
