# /info端点信息配置
info:
  app:
    name: OpenDFL console
    version: 0.1

spring:
  profiles:
    include:
      - opendfl
      - frequency
      - requestlock
      - console
  redis:
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000ms

