console:
  redisPrefix: 'freqConsole'
  ifConsole: '1'
  tokenExpire: 3600
  consoleWhiteIp: none
  rolePermits:
    - role: admin
      ifView: 1
      ifClear: 1
      ifEvict: 1
    - role: user
      ifView: 1
  users:
    - username: admin
      pwd: admin
      role: admin
    - username: user
      pwd: user
      role: user
  #功能白名单用户
  whiteCodeUsers:
    login: none