#限制策略
frequency:
  redisPrefix: 'limitFreq'
  ifActive: '1'
  white:
    items: 'whiteIp,whiteUser,'
    ips: 'none'
    users: 'none'
  black:
    items: 'blackIp,blackUser,'
    ips: '192.168.2.154'
    users: 'none'
  limit:
    items: 'limit,userCount,userIp,ipUser,'
    #IP限制是否区分功能，如果不区分功能，则缓存有效期相同，以及ip数或用户数共享
    ipLimitSplitFunction: '0'
    #间格时间内超限日志，例如>=3600时超限后的每次访问都将记录
    outLimitLogTime: 3600
    #基于uri的限制
    uriConfigs:
      - uri: /frequencyTest/serverTimeUri
        time: 5
        limit: 8
        attrName: account
      - uri: /frequencyTest/serverTimeUri
        time: 3600
        limit: 30
        userIp: 7
        ipUser: 7
        attrName: account
    #基于注解的频率限制
    frequencyConfigs:
      - name: serverTimeFreq
        time: 5
        limit: 10