# /info端点信息配置
info:
  app:
    name: OpenDFL Open Ddstributed frequency limitation
    version: 0.1

spring:
  redis:
    host: 10.0.8.3
    password: ''
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000ms

logging:
  level:
    root: INFO
    com:
      ccs:
        opendfl: DEBUG