opendfl:
  #支持关闭这个服务的Redis配置，由外其他类提供
  redisCacheEnable: 1
  defaultAttrName: userId
  defaultDeviceId: device_id
  baseLimit:
    pageSizeMax: 20
    pageNumMax: 20
    totalRowMax: 100
    #默认查询时段最大天数
    searchDateMaxDay: 90